fix docker CI image
Ubuntu 18.04 contains python 3.6.9 and installation of cvxpy fails with

RuntimeError: Python version >= 3.7 required.

Fix by updating to Ubuntu 20.04.